[build]
  # Netlify Next.js plugin otomatik olarak halleder
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Essential Next.js plugin - routing'i otomatik halleder
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Static site için basit redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "" 